# Generated by Django 3.0 on 2019-12-17 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Recipe name', max_length=255, verbose_name='Name')),
                ('user', models.OneToOneField(help_text='Recipe owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_text', models.CharField(help_text='Step description', max_length=255, verbose_name='Step Description')),
                ('recipe', models.ForeignKey(help_text='Recipe this step is a part of', on_delete=django.db.models.deletion.CASCADE, to='core.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Ingredient description', max_length=255, verbose_name='Ingredient Description')),
                ('recipe', models.ForeignKey(help_text='Recipe this ingredient is a part of', on_delete=django.db.models.deletion.CASCADE, to='core.Recipe')),
            ],
        ),
    ]
